// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsCb-Vgnb93WfNt3dogjF7r1A6vxY1T7A',
    appId: '1:639318129098:web:bf98bb66a0ce5f7c96f733',
    messagingSenderId: '639318129098',
    projectId: 'valgrow-app',
    authDomain: 'valgrow-app.firebaseapp.com',
    storageBucket: 'valgrow-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATKzPAHo6h38ZayTb_M-TQImS1uITzAaE',
    appId: '1:202425696620:android:d59e8fff120141a6b1f349',
    messagingSenderId: '202425696620',
    projectId: 'valgrow-new',
    storageBucket: 'valgrow-new.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCC0uPtgE0-o_ME8ZhUqNe0pdumud5OPbY',
    appId: '1:202425696620:ios:69f6e9688d407927b1f349',
    messagingSenderId: '202425696620',
    projectId: 'valgrow-new',
    storageBucket: 'valgrow-new.firebasestorage.app',
    iosBundleId: 'com.example.valgrowUi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCn_0csa2pNUKKHZ1BMC8QOJ8QqNWTcgoM',
    appId: '1:639318129098:ios:9e761e804ee69abc96f733',
    messagingSenderId: '639318129098',
    projectId: 'valgrow-app',
    storageBucket: 'valgrow-app.firebasestorage.app',
    iosBundleId: 'com.example.valgrowUi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCsCb-Vgnb93WfNt3dogjF7r1A6vxY1T7A',
    appId: '1:639318129098:web:c287ea74445a5c9896f733',
    messagingSenderId: '639318129098',
    projectId: 'valgrow-app',
    authDomain: 'valgrow-app.firebaseapp.com',
    storageBucket: 'valgrow-app.firebasestorage.app',
  );
}